version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install --upgrade pip
      - pip install sagemaker
      - pip install boto3
      - pip install pandas==1.5.1
      - pip install lxml
      
  build:
    commands:
      - python PreprocessingPipeline.py
  post_build:
    commands:
      - echo Build completed on `date`
